sudo: required
services:
 - docker

before_install:
 - docker build -t omriwallach/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true omriwallach/react-test npm test -- --coverage

after_success:
 - docker build -t omriwallach/multi-client ./client
 - docker build -t omriwallach/multi-nginx ./nginx
 - docker build -t omriwallach/multi-server ./server
 - docker build -t omriwallach/multi-worker ./worker
 # Log to docker cli 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Push the images to docker hub
 - docker push omriwallach/multi-client
 - docker push omriwallach/multi-nginx
 - docker push omriwallach/multi-server
 - docker push omriwallach/multi-worker
 # pull the images in aws
 deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-697082700401
  bucket_path: docker-multi
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
   secure: $AWS_SECRET_KEY